lps/map/routes.py
from flask import Blueprint, current_app, render_template, jsonify
from flask_login import login_required
from lps.models import Unit, LocatorPoint
from lps.schemas import UnitSchema, LocatorPointSchema


map_bp = Blueprint("map_bp", __name__, url_prefix="/map", template_folder="templates")


@map_bp.route('/', methods=["GET"])
@login_required
def map():
    units_q = Unit.query.all()
    units = UnitSchema(many=True).dump(units_q)

    return render_template('map.html', units=units, google_api_key=current_app.config['GOOGLE_CLOUD_API_KEY']), 200


@map_bp.route('/locators', methods=["GET"])
@login_required
def map_locators():
    points_q = LocatorPoint.query.all()
    points = LocatorPointSchema(many=True).dump(points_q)
    return jsonify(points), 200

lps/templates/index.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div class="container py-5">
        <div class="jumbotron p-5 bg-dark rounded-3">
            <div class="container-fluid text-white">
                <h1>Welcome to the LPS Platform!</h1>
                <br />
                <a href="{{ url_for('map_bp.map') }}"><button class="btn btn-primary btn-lg">View Map</button></a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

lps/templates/login.html
{% extends 'base.html' %}

{% block navbar %}
<div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Login</h5>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
</div>
<div class="offcanvas-body">
</div>
{% endblock %}

{% block content %}
<div class="container">
    <h1>Log In</h1>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-danger" role="alert">
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    {% endwith %}

    <form action="/login" method="POST" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=32) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        {{ form.submit() }}
    </form>
</div>
{% endblock %}